# Generated by Django 4.1.1 on 2022-12-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_date', models.DateField()),
                ('disease_name', models.CharField(max_length=50)),
                ('disease_cure', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'history',
                'managed': False,
            },
        ),

    ]
