# Generated by Django 4.1 on 2022-12-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="disease",),
        migrations.DeleteModel(name="status",),
        migrations.DeleteModel(name="user",),
    ]
