# Generated by Django 3.2.16 on 2022-12-14 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_history'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='history',
            table=None,
        ),
    ]
