# Generated by Django 4.1 on 2022-12-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0002_log_delete_history"),
    ]

    operations = [
        migrations.AlterModelOptions(name="log", options={"managed": False},),
    ]
