# Generated by Django 3.2.16 on 2022-12-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_disease_history_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='disease',
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
