# Generated by Django 4.1 on 2022-12-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0004_alter_log_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="log", table="log",),
    ]
