# Generated by Django 4.1 on 2022-12-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0006_alter_log_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="history",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("reg_date", models.DateField()),
                ("disease_name", models.CharField(max_length=50)),
                ("disease_cure", models.CharField(max_length=200)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="%Y/%m/%d"),
                ),
            ],
            options={"db_table": "log_history", "managed": False,},
        ),
        migrations.DeleteModel(name="log",),
    ]
