# Generated by Django 4.1.3 on 2022-12-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=40, null=True)),
                ("imgfile", models.ImageField(blank=True, null=True, upload_to="")),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
    ]
