# Generated by Django 3.2.16 on 2022-12-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='image',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
    #             ('image_reg_date', models.DateField(auto_now=True, null=True)),
    #         ],
    #     ),
    # ]
