# Generated by Django 4.1.3 on 2022-12-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("confirm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("image_reg_date", models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(name="Upload",),
    ]
