# Generated by Django 3.2.16 on 2022-12-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='yolo/'),
        ),
    ]
